#!/usr/bin/env bash
# brain.fm

clear

TRACK="/home/dan/Media/SOUND/Brain.FM/brainfm-deep-focus.mp4"
MESG="🎶  Now Playing: Brain.FM 🧠 - Deep Focus  🎶" > "/tmp/playmsg.txt"
TMPF="/tmp/playmesg.txt"

ascii_center "/home/dan/Documents/asclepius"
ascii_center "/home/dan/Documents/todo"
ascii_box "$MESG" > "$TMPF"
echo
ascii_center "$TMPF"

# Random start between 0% and 98%
START_PERCENT=$((RANDOM % 98))

mpv \
    --start="${START_PERCENT}%" \
    --no-video --term-osd-bar \
    --msg-level=cplayer=warn \
    --loop=inf --volume=75 \
    --display-tags=no \
    "${TRACK}"
